version: '3.2'

services:

  wordpress:
    build:
      context: ./docker/wordpress
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - www:/var/www/html:rw
    ulimits:
      core:
        soft: -1 
        hard: -1
    networks:
      - wordpress-infra

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./conf/nginx-default-host.conf:/etc/nginx/conf.d/default.conf:ro
      - www:/var/www/html:ro
    networks:
      wordpress-infra:
        aliases:
          - wordpress-sandbox.discoverops.com

  mysql:
    image: pataquets/mysql-proxy
    depends_on:
      - mysql-backend
    command: >
      --keepalive --log-level=debug
      --proxy-backend-addresses=mysql-backend
      --proxy-lua-script=/usr/proxy-script.lua
      --plugins=proxy
    volumes:
      - ./conf/proxy-script.lua:/usr/proxy-script.lua
      - type: volume
        source: querylog
        target: /log
        read_only: false 
        volume:
          nocopy: false
    networks:
      - wordpress-infra

  mysql-logger:
    image: alpine
    restart: always
    depends_on:
      - mysql
    volumes:
      - querylog:/log:ro
    command: 'tail -f /log/query.log'

  mysql-backend:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data:/docker-entrypoint-initdb.d:ro
    networks:
      - wordpress-infra

  firefox:
    image: selenium/node-chrome-debug:3.11.0-californium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
    ports:
      - "15900:5900"
    networks:
      - wordpress-infra

  selenium-hub:
    image: selenium/hub:3.11.0-californium
    ports:
      - "14444:4444"
    networks:
      - wordpress-infra

  client:
    build:
      context: ./docker/client
    networks:
      - wordpress-infra

volumes:
  www:
  querylog:

networks:
  wordpress-infra:

