version: '3.2'

services:

  wordpress:
    build:
      context: ./docker/wordpress
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - www:/var/www/html:rw
    networks:
      - wordpress-infra

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./conf/nginx-default-host.conf:/etc/nginx/conf.d/default.conf:ro
      - www:/var/www/html:ro
    networks:
      wordpress-infra:
        aliases:
          - wordpress-sandbox.discoverops.com

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data:/docker-entrypoint-initdb.d:ro
    networks:
      - wordpress-infra

  firefox:
    image: selenium/node-chrome-debug:3.11.0-californium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
    ports:
      - "15900:5900"
    networks:
      - wordpress-infra

  selenium-hub:
    image: selenium/hub:3.11.0-californium
    ports:
      - "14444:4444"
    networks:
      - wordpress-infra

  client:
    build:
      context: ./docker/client
    networks:
      - wordpress-infra

volumes:
  www:

networks:
  wordpress-infra:

