version: '3.2'

services:

  wordpress:
    image: wordpress:fpm
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - www:/var/www/html:rw

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./conf/nginx-default-host.conf:/etc/nginx/conf.d/default.conf:ro
      - www:/var/www/html:ro
    ports:
      - "8080:80"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data:/docker-entrypoint-initdb.d:ro
volumes:
  www:

